config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, shallow: true do
    resources :reviews do
      resources :endorsements
    end
  end

  root "restaurants#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/endoresment.rb
class Endoresment < ApplicationRecord

  belongs_to :review
  belongs_to :user
  
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


  belongs_to :user
  has_many :reviews

  has_many :reviews, dependent: :destroy
  validates :name, length: {minimum: 3}, uniqueness: true

  def build_review(attributes = {}, user)
    review = reviews.build(attributes)
    review.user = user
    review
  end
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :restaurant
  has_many :endorsments

  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }
  validates :rating, inclusion: (1..5)
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :restaurants
  has_many :reviews
  has_many :endorsments
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email || "#{auth.uid}@facebook.com"
      user.password = Devise.friendly_token[0,20]
    end
  end

  def has_reviewed?(restaurant)
    reviewed_restaurants.include? restaurant
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

  def create
    @review = Review.find(params[:review_id])
    @review.endorsments.create
    redirect '/'
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @user = current_user if current_user
    @restaurants = Restaurant.all
    @reviews = Review.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    user = current_user
    @restaurant = user.restaurants.new(restaurants_params)
    if @restaurant.save
      redirect_to '/restaurants'
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurants_params)

    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end

  private
  def restaurants_params
    params.require(:restaurant).permit(:name, :description, :image)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    user = current_user
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.new
  end

  def create
    user = current_user
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.build_review review_params, current_user
    if @review.save
      redirect_to restaurants_path
    else
      if @review.errors[:user]
        redirect_to restaurants_path, alert: 'You have already reviewd this restaurant'
      else
        render 'new'
      end
    end
  end

  def destroy
    # @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = 'Review successfully destroyed'
    redirect_to '/restaurants'
  end


  private
  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end

  def build_review(attributes = {}, user)
    review = reviews.build(attributes)
    review.user = user
    review
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])
      @user.email = "#{@user.uid}@facebook.com"
      @user.save
      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path %>
    <%= link_to "Sign up", new_user_registration_path %>
    <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
  <% end %>
  <%= notice %>
  <%= yield %>
</body>
</html>

app/views/restaurants/edit.html.haml
=form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.label :description
  = f.text_area :description
  = f.submit "Update Restaurant"

app/views/restaurants/index.html.haml
- if @restaurants.any?
  - @restaurants.each do |restaurant|
    #listing
      %h2= link_to restaurant.name, restaurant_path(restaurant)
      = image_tag restaurant.image.url(:thumb)
      %p= restaurant.description
      - restaurant.reviews.each do |review|
        %p= review.thoughts
        %p= link_to "Endorse Review", review_endorsements_path(review), method: :post
        - if @user
          - if @user.reviews.include?(review)
            %p= link_to "Delete Review", review_path(review), method: :delete
      - if @user
        - if @user.restaurants.include?(restaurant)
          %p= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)
          %p= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete
        - unless @user.has_reviewed?(restaurant)
          %p= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant)
- else
  %h1 No restaurants yet!

#newRestaurant
= link_to 'Add a restaurant', new_restaurant_path

app/views/restaurants/new.html.haml
- if @restaurant.errors.any?
  %section#errors
    %h2
      = pluralize @restaurant.errors.count, 'error'
      prohibited this restaurant from being saved:
    %ul
      - @restaurant.errors.full_messages.each do |message|
        %li= message

= form_for @restaurant, html: {multipart: true} do |f|
  = f.label :name
  = f.text_field :name
  = f.label :description
  = f.text_area :description
  = f.file_field :image
  = f.submit

app/views/restaurants/show.html.haml
%p= @restaurant.name
%p= @restaurant.description

app/views/reviews/new.html.haml
= form_for [@restaurant, @review] do |f|
  = f.label :thoughts
  = f.text_area :thoughts
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit 'Leave Review'